r"""
Duplicate Findings Analysis Tool
================================

This script performs within-tool duplicate analysis and cross-tool overlap
analysis using the normalized findings dataset generated by the SARIF
comparison framework.

The script processes security findings extracted from CodeQL and Semgrep
and generates structured Markdown tables for duplicate cluster evaluation
and overlap analysis.

Main features:

  - security finding filtering
  - within-tool duplicate cluster analysis
  - duplicate classification by rule and category behavior
  - cross-tool overlap analysis
  - severity agreement analysis
  - Markdown table generation for evaluation datasets

Input file:
    comparison_output/all_findings.csv

Generated output:
    comparison_output/duplicate_findings_data.md

Run:
    python scripts/generate_duplicate_data.py
"""

import csv
import argparse
from pathlib import Path
from collections import defaultdict, Counter

LINE_TOLERANCE = 2
OVERLAP_TOLERANCE = 5

# ---------------------------------------------------------------------------
# Repository-relative paths
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

INPUT_FILE = BASE_DIR / "comparison_output" / "all_findings.csv"

OUTPUT_FILE = (
    BASE_DIR
    / "comparison_output"
    / "duplicate_findings_data.md"
)

def load_security_findings(path):
    findings = []
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row.get("kind") != "security":
                continue
            row["line_int"] = int(row["line"]) if row["line"].isdigit() else 0
            findings.append(row)
    return findings


def find_clusters(tool_findings, tolerance=LINE_TOLERANCE):
    by_file = defaultdict(list)
    for f in tool_findings:
        by_file[f["file"]].append(f)          # full path

    clusters = []
    for _, items in by_file.items():
        items.sort(key=lambda x: x["line_int"])
        current = []
        for item in items:
            if not current:
                current = [item]
            elif abs(item["line_int"] - current[-1]["line_int"]) <= tolerance:
                current.append(item)
            else:
                if len(current) > 1:
                    clusters.append(current)
                current = [item]
        if len(current) > 1:
            clusters.append(current)
    return clusters


def classify_type(cluster):
    lines = set(c["line_int"] for c in cluster)
    rules = set(c["rule_id"] for c in cluster)
    cats = set(c["category"] for c in cluster)
    same_line = len(lines) == 1
    same_rule = len(rules) == 1
    if same_line and same_rule:
        return "Same line, same rule (literal duplicate)"
    if same_line and len(cats) == 1:
        return "Same line, same category, different rules"
    if same_line:
        return "Same line, different categories"
    if same_rule:
        return "Adjacent lines, same rule"
    if len(cats) == 1:
        return "Adjacent lines, same category, different rules"
    return "Adjacent lines, different categories"


def short_rule(rule_id):
    parts = rule_id.split(".")
    return rule_id if len(parts) <= 2 else parts[-1]


def find_overlaps(findings, tolerance=OVERLAP_TOLERANCE):
    groups = defaultdict(lambda: {"CodeQL": [], "Semgrep": []})
    for f in findings:
        base = f["file"].split("/")[-1]
        groups[(f["category"], base)][f["tool"]].append(f)

    overlaps = []
    for (cat, base), t in groups.items():
        if not (t["CodeQL"] and t["Semgrep"]):
            continue
        for cq in t["CodeQL"]:
            done = False
            for sg in t["Semgrep"]:
                if abs(cq["line_int"] - sg["line_int"]) <= tolerance:
                    overlaps.append({
                        "category": cat, "file": base,
                        "cq_line": cq["line_int"], "sg_line": sg["line_int"],
                        "cq_sev": cq["severity"], "sg_sev": sg["severity"],
                    })
                    done = True
                    break
            if done:
                break
    overlaps.sort(key=lambda o: (o["cq_sev"] != o["sg_sev"], o["category"]))
    return overlaps


def labelled(clusters, prefix):
    out = []
    for i, c in enumerate(sorted(clusters,
                                 key=lambda x: (x[0]["file"], x[0]["line_int"])), 1):
        out.append((f"{prefix}-{i}", c))
    return out


def build_data(findings):
    cq = [f for f in findings if f["tool"] == "CodeQL"]
    sg = [f for f in findings if f["tool"] == "Semgrep"]

    cq_clusters = find_clusters(cq)
    sg_clusters = find_clusters(sg)

    cq_total, sg_total = len(cq), len(sg)
    cq_in = sum(len(c) for c in cq_clusters)
    sg_in = sum(len(c) for c in sg_clusters)
    cq_n, sg_n = len(cq_clusters), len(sg_clusters)
    cq_distinct = cq_total - (cq_in - cq_n)
    sg_distinct = sg_total - (sg_in - sg_n)
    cq_pct = round(cq_in / cq_total * 100) if cq_total else 0
    sg_pct = round(sg_in / sg_total * 100) if sg_total else 0

    cq_types = Counter(classify_type(c) for c in cq_clusters)
    sg_types = Counter(classify_type(c) for c in sg_clusters)
    type_order = [
        "Same line, same rule (literal duplicate)",
        "Same line, same category, different rules",
        "Same line, different categories",
        "Adjacent lines, same rule",
        "Adjacent lines, same category, different rules",
        "Adjacent lines, different categories",
    ]

    overlaps = find_overlaps(findings)
    agree = sum(1 for o in overlaps if o["cq_sev"] == o["sg_sev"])

    L = []
    w = L.append

    w("# Within-Tool Duplicate Findings: Data Tables\n")
    w("_Generated by `generate_duplicate_data.py` from `all_findings.csv`. "
      "This file contains computed data only. Interpretation is in the "
      "duplicate_findings_insights.md document._\n")
    w("---\n")

    # Table 1: summary
    w("## Table 1: Summary\n")
    w("| Metric | CodeQL | Semgrep |")
    w("|-|-|-|")
    w(f"| Total security findings | {cq_total} | {sg_total} |")
    w(f"| Duplicate clusters | {cq_n} | {sg_n} |")
    w(f"| Findings inside a cluster | {cq_in} | {sg_in} |")
    w(f"| Share of output duplicated | {cq_pct}% | {sg_pct}% |")
    w(f"| Largest cluster size | {max((len(c) for c in cq_clusters), default=0)} "
      f"| {max((len(c) for c in sg_clusters), default=0)} |")
    w(f"| Distinct issues after de-duplication | {cq_distinct} | {sg_distinct} |\n")

    # Table 2: cluster types
    w("## Table 2: Duplicate Cluster Types\n")
    w("| Cluster type | CodeQL | Semgrep |")
    w("|-|-|-|")
    for t in type_order:
        w(f"| {t} | {cq_types.get(t,0)} | {sg_types.get(t,0)} |")
    w(f"| Total | {cq_n} | {sg_n} |\n")

    # Table 3: CodeQL clusters
    w("## Table 3: CodeQL Duplicate Clusters\n")
    w("| ID | File | Lines | Type | Rules |")
    w("|-|-|-|-|-|")
    for cid, c in labelled(cq_clusters, "CQ"):
        f0 = c[0]
        lines = ", ".join(str(x) for x in sorted(set(y["line_int"] for y in c)))
        rules = " + ".join(sorted(set(short_rule(x["rule_id"]) for x in c)))
        w(f"| {cid} | `{f0['file']}` | {lines} | {classify_type(c)} | `{rules}` |")
    w("")

    # Table 4: Semgrep clusters
    w("## Table 4: Semgrep Duplicate Clusters\n")
    w("| ID | File | Lines | Type | Rules |")
    w("|-|-|-|-|-|")
    for cid, c in labelled(sg_clusters, "SG"):
        f0 = c[0]
        lines = ", ".join(str(x) for x in sorted(set(y["line_int"] for y in c)))
        rules = " + ".join(sorted(set(short_rule(x["rule_id"]) for x in c)))
        w(f"| {cid} | `{f0['file']}` | {lines} | {classify_type(c)} | `{rules}` |")
    w("")

    # Table 5: cross-tool overlap
    w("## Table 5: Cross-Tool Overlap\n")
    w(f"_Severity agreement: {agree} of {len(overlaps)} overlaps agree._\n")
    w("| Category | File | CodeQL line | Semgrep line | CodeQL sev. | Semgrep sev. |")
    w("|-|-|-|-|-|-|")
    for o in overlaps:
        w(f"| {o['category']} | {o['file']} | {o['cq_line']} | {o['sg_line']} | "
          f"{o['cq_sev']} | {o['sg_sev']} |")
    w("")

    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default=str(INPUT_FILE))
    ap.add_argument("--output", default=str(OUTPUT_FILE))
    args = ap.parse_args()
    findings = load_security_findings(args.input)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(build_data(findings))
    print(f"Wrote {args.output} from {args.input} ({len(findings)} security findings)")


if __name__ == "__main__":
    main()